name: setup-azurefunctions-action
description: Set up an Azure Functions app for testing
inputs:
  publish-profile-env-name:
    description: The name of the environment variable to fill with the publish profile for the Functions App
    required: true
  azure-credentials:
    description: The JSON blob containing the Azure login credentials. Required setting up the RBAC assignments.
    required: true
  env-vars-to-promote:
    description: A comma-separated list of environment variables in the Actions environment to promote to App Settings in the Functions app
    required: false
    default: ''
  tag:
    description: The name of the component Azure Functions app is being used for. The Functions app is tagged with this value.
    required: true
outputs:
  app-name:
    description: The app name for the created Functions app
  publish-profile:
    description: The publish profile for the created Functions app
  hostname:
    description: The primary host name for the created Functions app
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
